classdef dp_node_core < ...
        ...
        dp_node_core_dpm & ...
        dp_node_core_log & ...
        dp_node_core_central & ...
        dp_node_core_roi & ...
        dp_node_core_syscmd & ...
        dp_node_core_navigator & ...
        dp_node_core_run_fun & ...
        dp_node_core_tmp & ...
        dp_node_core_cache & ...
        dp_node_core_connect & ...
        handle 

end