classdef dp_node_workflow_tmp < dp_node_workflow

    % switches processing to temporary folder, deletes intermediaries,
    % copies selected fields to op


    methods

        function obj = dp_node_workflow_tmp(nodes, fields, name)

            % warning: generates a non-deterministic pipeline
            tmp_name = cat(2, 'tmp', num2str(keyHash(randi(2^16, 10))));

            nodes = {...
                dp_node_io(tmp_name, @(x) struct(...
                    'tmp', dp_node().make_tmp(), ...
                    'bp', x.bp, ...
                    'op', x.op)), ...
                dp_node_io_mem_store(tmp_name), ...
                dp_node_io('bp', @(x) x.(tmp_name).tmp.bp), ...
                dp_node_io('op', @(x) fullfile(x.bp, x.id)), ...
                nodes{:}, ...
                dp_node_io_mem_retrieve(tmp_name), ...
                dp_node_io_append({...
                    {'bp', @(x) x.(tmp_name).bp}, ...
                    {'op', @(x) x.(tmp_name).op}}), ...
                dp_node_copy(fields).set('do_i2o_pass', 1), ...
                dp_node_io('tmp', @(x) x.(tmp_name).tmp), ...
                dp_node_io_select(fields)}; %#ok<CCAT>


            obj = obj@dp_node_workflow(nodes, name);
            

            obj.output_test = fields; 

        end

    end


end